export const DataUsage = () => {
  return (
    <div>
      <h2 className="text-2xl font-bold mt-8 mb-4">2. How We Use Your Information</h2>
      <p className="font-semibold">2.1. Service Provision:</p>
      <ul className="list-disc pl-6 mt-4">
        <li>To provide, maintain, and improve our services</li>
        <li>To process your transactions and maintain your accounts</li>
        <li>To verify your identity and prevent fraud</li>
        <li>To provide customer support and respond to inquiries</li>
        <li>To send service-related notifications and updates</li>
        <li>To customize and optimize your experience</li>
        <li>To analyze usage patterns and improve functionality</li>
        <li>To maintain the security and integrity of our platform</li>
      </ul>

      <h2 className="text-2xl font-bold mt-8 mb-4">3. Information Sharing and Disclosure</h2>
      <p className="font-semibold">3.1. Third-Party Service Providers:</p>
      <ul className="list-disc pl-6 mt-4">
        <li>Cloud hosting and infrastructure providers</li>
        <li>Payment processors and financial institutions</li>
        <li>Identity verification services</li>
        <li>Analytics and monitoring services</li>
        <li>Customer support platforms</li>
        <li>Marketing and advertising partners</li>
        <li>Professional advisors and consultants</li>
      </ul>

      <p className="font-semibold mt-4">3.2. Legal Requirements:</p>
      <ul className="list-disc pl-6 mt-4">
        <li>To comply with applicable laws and regulations</li>
        <li>In response to valid legal requests from authorities</li>
        <li>To protect our rights, privacy, safety, or property</li>
        <li>To detect and prevent fraud or illegal activities</li>
        <li>In connection with legal proceedings or investigations</li>
      </ul>

      <p className="font-semibold mt-4">3.3. Data Processing Agreement:</p>
      <ul className="list-disc pl-6 mt-4">
        <li>We process data in accordance with GDPR, CCPA, and other applicable regulations</li>
        <li>We maintain appropriate technical and organizational security measures</li>
        <li>We conduct regular security audits and vulnerability assessments</li>
        <li>We require our sub-processors to maintain similar security standards</li>
        <li>We maintain records of all data processing activities</li>
      </ul>

      <p className="font-semibold mt-4">3.4. International Data Transfers:</p>
      <ul className="list-disc pl-6 mt-4">
        <li>Data may be transferred to and processed in multiple jurisdictions</li>
        <li>We ensure appropriate safeguards for international data transfers</li>
        <li>We comply with Standard Contractual Clauses and other transfer mechanisms</li>
        <li>Users consent to international data transfers as necessary for service provision</li>
      </ul>

      <h2 className="text-2xl font-bold mt-8 mb-4">4. Data Retention and Deletion</h2>
      <p className="font-semibold">4.1. Retention Period:</p>
      <ul className="list-disc pl-6 mt-4">
        <li>We retain data as long as necessary for service provision</li>
        <li>Legal and regulatory compliance requirements may extend retention</li>
        <li>Backup and archive copies may be retained longer</li>
        <li>Some data may be anonymized rather than deleted</li>
        <li>Deletion requests are processed within 30 days</li>
      </ul>

      <h2 className="text-2xl font-bold mt-8 mb-4">5. Your Rights and Choices</h2>
      <p>By using our service, you explicitly acknowledge and agree that:</p>
      <ul className="list-disc pl-6 mt-4">
        <li>We may process your data as described in this policy</li>
        <li>You have no expectation of privacy beyond what is explicitly stated</li>
        <li>Changes to the policy may be made at our discretion</li>
        <li>You are responsible for reviewing policy updates</li>
        <li>Continued use constitutes acceptance of changes</li>
      </ul>

      <h2 className="text-2xl font-bold mt-8 mb-4">6. Data Breach Notification</h2>
      <p className="font-semibold">6.1. Notification Process:</p>
      <ul className="list-disc pl-6 mt-4">
        <li>We will notify affected users within 72 hours of discovering a breach</li>
        <li>Notifications will include the nature and extent of the breach</li>
        <li>We will cooperate with law enforcement and regulatory authorities</li>
        <li>We maintain an incident response plan and regularly test it</li>
      </ul>

      <h2 className="text-2xl font-bold mt-8 mb-4">7. Intellectual Property Rights</h2>
      <p className="font-semibold">7.1. Ownership:</p>
      <ul className="list-disc pl-6 mt-4">
        <li>All content and data generated by the service remains our property</li>
        <li>Users retain rights to their uploaded content but grant us a license to use it</li>
        <li>Our trademarks and branding may not be used without permission</li>
        <li>Derivative works based on our data require explicit written permission</li>
      </ul>
    </div>
  );
};
